name: Create and Push Multi-Arch Manifest
description: >
  Combines individual single-architecture MCPM Docker images into a single
  multi-architecture manifest and pushes it to the GitHub Container Registry (GHCR).
  Also allows for the manifest to be tagged with one or more meaningful tags.
inputs:
  image:
    description: Full image name in GHCR (e.g., ghcr.io/owner/mcpm).
    required: true
  ref_name:
    description: Git reference name or release tag used for version tagging.
    required: true
  tags:
    description: Whitespace-separated list of tags to apply to the final manifest.
    required: true
  token:
    description: GitHub token used for registry login.
    required: true

runs:
  using: composite
  steps:
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Create and push multi-arch manifest
      shell: bash
      run: |
        TAGS="${{ inputs.tags }}"

        echo "Creating manifest for: ${{ inputs.image }}"
        echo "Tags:"
        echo "${TAGS}"

        docker buildx imagetools create \
          $(echo "${TAGS}" | sed 's/^/-t /') \
          ${{ inputs.image }}:amd64 \
          ${{ inputs.image }}:arm64

    - name: Inspect final manifest
      shell: bash
      run: >
        TAGS="${{ inputs.tags }}"
        TAG=$(echo "$TAGS" | awk '{print $1}')
        echo "Inspecting: $TAG"
        docker buildx imagetools inspect ${IMAGE}
